package com.sf.ieca.business.sfexpress.appservice.impl;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import com.sf.ieca.business.sfexpress.appservice.SfexpressService;
import com.xuanfeiyang.erp.App;

import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-03-18T14:44:52.651+08:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "SfexpressServiceImplService", 
                  wsdlLocation = "http://120.24.60.8:8003/CBTA/ws/sfexpressService?wsdl",
                  targetNamespace = "http://impl.appservice.sfexpress.business.ieca.sf.com/") 
public class SfexpressServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.appservice.sfexpress.business.ieca.sf.com/", "SfexpressServiceImplService");
    public final static QName SfexpressServiceImplPort = new QName("http://impl.appservice.sfexpress.business.ieca.sf.com/", "SfexpressServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL(App.getConfig("express.sf.europe.url"));
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SfexpressServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://120.24.60.8:8003/CBTA/ws/sfexpressService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SfexpressServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SfexpressServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SfexpressServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SfexpressServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SfexpressServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SfexpressServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns SfexpressService
     */
    @WebEndpoint(name = "SfexpressServiceImplPort")
    public SfexpressService getSfexpressServiceImplPort() {
        return super.getPort(SfexpressServiceImplPort, SfexpressService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SfexpressService
     */
    @WebEndpoint(name = "SfexpressServiceImplPort")
    public SfexpressService getSfexpressServiceImplPort(WebServiceFeature... features) {
        return super.getPort(SfexpressServiceImplPort, SfexpressService.class, features);
    }

}
