package com.sf.ieca.business.sfexpress.appservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-03-18T14:44:52.643+08:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://appservice.sfexpress.business.ieca.sf.com/", name = "SfexpressService")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface SfexpressService {

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://appservice.sfexpress.business.ieca.sf.com/", partName = "return")
    public java.lang.String sfexpressService(
        @WebParam(partName = "xml", name = "xml")
        java.lang.String xml,
        @WebParam(partName = "verifyCode", name = "verifyCode")
        java.lang.String verifyCode
    );
}
