package com.sf.ieca.business.sfexpress.appservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.sf.ieca.business.sfexpress.appservice.impl.SfexpressServiceImplService;

/**
 * This class was generated by Apache CXF 3.0.4 2015-03-18T14:44:52.593+08:00
 * Generated source version: 3.0.4
 * 
 */
public final class SfexpressService_SfexpressServiceImplPort_Client {
	private static final Logger logger = LoggerFactory
			.getLogger(SfexpressService_SfexpressServiceImplPort_Client.class);
	private static final QName SERVICE_NAME = new QName("http://impl.appservice.sfexpress.business.ieca.sf.com/",
			"SfexpressServiceImplService");

	private SfexpressService_SfexpressServiceImplPort_Client() {
	}

	public static String execute(String xml, String verifyCode) {
		URL wsdlURL = SfexpressServiceImplService.WSDL_LOCATION;

		SfexpressServiceImplService ss = new SfexpressServiceImplService(wsdlURL, SERVICE_NAME);
		SfexpressService port = ss.getSfexpressServiceImplPort();

		return port.sfexpressService(xml, verifyCode);
	}
	
	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = SfexpressServiceImplService.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				logger.error(e.getMessage());
			}
		}

		SfexpressServiceImplService ss = new SfexpressServiceImplService(wsdlURL, SERVICE_NAME);
		SfexpressService port = ss.getSfexpressServiceImplPort();

		{
			logger.debug("Invoking sfexpressService...");
			java.lang.String _sfexpressService_xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Request service=\"OrderService\" lang=\"zh-CN\"><Head>7550363971</Head><Body><Order orderid=\"318145103\" express_type=\"A1\" j_company=\"深圳市轩飞扬贸易有限公司\" j_contact=\"陈飞\" j_tel=\"18925220117\" j_mobile=\"18925220117\" j_address=\"广东省深圳市宝安区52区新安五路宝裕大厦8楼\" d_company=\"us Lee\" d_contact=\"us Lee\" d_tel=\"123123123123\" d_mobile=\"123123123123\" d_address=\"31 Harefoot close\" parcel_quantity=\"1\" j_province=\"广东省\" j_city=\"深圳市\" d_province=\"\" d_city=\"Northampton\" j_country=\"CN\" j_post_code=\"518100\" d_country=\"US\" d_post_code=\"XXXX\" cargo_total_weight=\"1.0\" returnsign=\"Y\" d_email=\"t@r.com\" operate_flag=\"0\" j_county=\"\" d_county=\"\" declared_value=\"\" d_deliverycode=\"\"><Cargo name=\"挂钟\" hscode=\"123123123\" ename=\"Wall Clocks\" unit=\"PCE\" count=\"1\" amount=\"10\" weight=\"1.0\"/></Order></Body></Request>";
			java.lang.String _sfexpressService_verifyCode = "MjJGMzBCQkQ3MTQ3RERFNzlCM0UyRjZCODVGQTE3NjI";
			java.lang.String _sfexpressService__return = port.sfexpressService(_sfexpressService_xml,
					_sfexpressService_verifyCode);
			logger.debug("sfexpressService.result=" + _sfexpressService__return);

		}

		System.exit(0);
	}

}
