package com.hlt.ws.service.hop.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.0.4 2015-11-18T10:33:55.714+08:00
 * Generated source version: 3.0.4
 * 
 */
public final class OrderOnlineService_OrderOnlineServicePort_Client {

	private static final QName SERVICE_NAME = new QName(
			"http://service.hop.service.ws.hlt.com/",
			"OrderOnlineServiceService");

	private OrderOnlineService_OrderOnlineServicePort_Client() {
	}

	private static OrderOnlineService getService() {
		URL wsdlURL = OrderOnlineServiceService.WSDL_LOCATION;
		OrderOnlineServiceService ss = new OrderOnlineServiceService(wsdlURL, SERVICE_NAME);
		return ss.getOrderOnlineServicePort();
	}
	
	public static CreateOrderResponse createAndAuditOrder(String userToken,
			CreateOrderRequest request) {
		OrderOnlineService port = getService();
		return port.createAndAuditOrder(userToken, request);
	}
	
	public static GetTransportWayListResponse getTransportWayList(String userToken) {
		OrderOnlineService port = getService();
		return port.getTransportWayList(userToken);
	}

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = OrderOnlineServiceService.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		OrderOnlineServiceService ss = new OrderOnlineServiceService(wsdlURL,
				SERVICE_NAME);
		OrderOnlineService port = ss.getOrderOnlineServicePort();

		{
			System.out.println("Invoking createOrder...");
			java.lang.String _createOrder_userToken = "";
			com.hlt.ws.service.hop.service.CreateOrderRequest _createOrder_createOrderRequest = null;
			com.hlt.ws.service.hop.service.CreateOrderResponse _createOrder__return = port
					.createOrder(_createOrder_userToken,
							_createOrder_createOrderRequest);
			System.out.println("createOrder.result=" + _createOrder__return);

		}
		{
			System.out.println("Invoking lookupOrder...");
			java.lang.String _lookupOrder_userToken = "";
			com.hlt.ws.service.hop.service.LookupOrderRequest _lookupOrder_lookupOrderRequest = null;
			com.hlt.ws.service.hop.service.LookupOrderResponse _lookupOrder__return = port
					.lookupOrder(_lookupOrder_userToken,
							_lookupOrder_lookupOrderRequest);
			System.out.println("lookupOrder.result=" + _lookupOrder__return);

		}
		{
			System.out.println("Invoking printOrder...");
			java.lang.String _printOrder_userToken = "";
			com.hlt.ws.service.hop.service.PrintOrderRequest _printOrder_printOrderRequest = null;
			com.hlt.ws.service.hop.service.PrintOrderResponse _printOrder__return = port
					.printOrder(_printOrder_userToken,
							_printOrder_printOrderRequest);
			System.out.println("printOrder.result=" + _printOrder__return);

		}
		{
			System.out.println("Invoking getTransportWayList...");
			java.lang.String _getTransportWayList_userToken = "";
			com.hlt.ws.service.hop.service.GetTransportWayListResponse _getTransportWayList__return = port
					.getTransportWayList(_getTransportWayList_userToken);
			System.out.println("getTransportWayList.result="
					+ _getTransportWayList__return);

		}
		{
			System.out.println("Invoking createAndAuditOrder...");
			java.lang.String _createAndAuditOrder_userToken = "";
			com.hlt.ws.service.hop.service.CreateOrderRequest _createAndAuditOrder_createOrderRequest = null;
			com.hlt.ws.service.hop.service.CreateOrderResponse _createAndAuditOrder__return = port
					.createAndAuditOrder(_createAndAuditOrder_userToken,
							_createAndAuditOrder_createOrderRequest);
			System.out.println("createAndAuditOrder.result="
					+ _createAndAuditOrder__return);

		}
		{
			System.out.println("Invoking deleteOrder...");
			java.lang.String _deleteOrder_userToken = "";
			long _deleteOrder_orderId = 0;
			com.hlt.ws.service.hop.service.DeleteOrderResponse _deleteOrder__return = port
					.deleteOrder(_deleteOrder_userToken, _deleteOrder_orderId);
			System.out.println("deleteOrder.result=" + _deleteOrder__return);

		}
		{
			System.out.println("Invoking calculateCharge...");
			java.lang.String _calculateCharge_userToken = "";
			com.hlt.ws.service.hop.service.CalculateChargeRequest _calculateCharge_calculateChargeRequest = null;
			com.hlt.ws.service.hop.service.CalculateChargeResponse _calculateCharge__return = port
					.calculateCharge(_calculateCharge_userToken,
							_calculateCharge_calculateChargeRequest);
			System.out.println("calculateCharge.result="
					+ _calculateCharge__return);

		}
		{
			System.out.println("Invoking auditOrder...");
			java.lang.String _auditOrder_userToken = "";
			long _auditOrder_orderId = 0;
			com.hlt.ws.service.hop.service.AuditOrderResponse _auditOrder__return = port
					.auditOrder(_auditOrder_userToken, _auditOrder_orderId);
			System.out.println("auditOrder.result=" + _auditOrder__return);

		}

		System.exit(0);
	}

}
