package com.hlt.ws.service.hop.service;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

import com.xuanfeiyang.erp.App;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-11-18T10:33:55.754+08:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "OrderOnlineServiceService", 
                  wsdlLocation = "http://kd.szice.net:8086/xms/services/order?wsdl",
                  targetNamespace = "http://service.hop.service.ws.hlt.com/") 
public class OrderOnlineServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.hop.service.ws.hlt.com/", "OrderOnlineServiceService");
    public final static QName OrderOnlineServicePort = new QName("http://service.hop.service.ws.hlt.com/", "OrderOnlineServicePort");
    static {
        URL url = null;
        try {
            url = new URL(App.getConfig("express.hulianyi.wsdl"));
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OrderOnlineServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://kd.szice.net:8086/xms/services/order?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OrderOnlineServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrderOnlineServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderOnlineServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrderOnlineServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrderOnlineServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrderOnlineServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns OrderOnlineService
     */
    @WebEndpoint(name = "OrderOnlineServicePort")
    public OrderOnlineService getOrderOnlineServicePort() {
        return super.getPort(OrderOnlineServicePort, OrderOnlineService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderOnlineService
     */
    @WebEndpoint(name = "OrderOnlineServicePort")
    public OrderOnlineService getOrderOnlineServicePort(WebServiceFeature... features) {
        return super.getPort(OrderOnlineServicePort, OrderOnlineService.class, features);
    }

}
