package com.sf.integration.expressservice.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-03-18T14:39:24.035+08:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://service.expressservice.integration.sf.com/", name = "IService")
@XmlSeeAlso({ObjectFactory.class})
public interface IService {

    @WebMethod
    @RequestWrapper(localName = "sfexpressService", targetNamespace = "http://service.expressservice.integration.sf.com/", className = "com.sf.integration.expressservice.service.SfexpressService")
    @ResponseWrapper(localName = "sfexpressServiceResponse", targetNamespace = "http://service.expressservice.integration.sf.com/", className = "com.sf.integration.expressservice.service.SfexpressServiceResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sfexpressService(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
