package com.sf.integration.expressservice.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 3.0.4 2015-03-18T14:39:23.992+08:00
 * Generated source version: 3.0.4
 * 
 */
public final class IService_CommonServicePort_Client {
	private static final Logger logger = LoggerFactory
			.getLogger(IService_CommonServicePort_Client.class);
	private static final QName SERVICE_NAME = new QName("http://service.expressservice.integration.sf.com/",
			"CommonServiceService");

	private IService_CommonServicePort_Client() {
	}

	public static String execute(String xml) {
		URL wsdlURL = CommonServiceService.WSDL_LOCATION;
		CommonServiceService ss = new CommonServiceService(wsdlURL, SERVICE_NAME);
		IService port = ss.getCommonServicePort();

		return port.sfexpressService(xml);
	}

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = CommonServiceService.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				logger.error(e.getMessage());
			}
		}

		CommonServiceService ss = new CommonServiceService(wsdlURL, SERVICE_NAME);
		IService port = ss.getCommonServicePort();

		{
			logger.debug("Invoking sfexpressService...");
			java.lang.String _sfexpressService_arg0 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Request service=\"OrderService\" lang=\"zh-CN\"><Head>szglkj,MoZYb2Lenno3N3TLfI[;</Head><Body><Order orderid=\"1318144036\" express_type=\"9\" j_company=\"Shenzhen X-Feiyang Co., Ltd.\" j_contact=\"Chenfei\" j_tel=\"18925220117\" j_mobile=\"18925220117\" j_address=\"8/F Bao’yu Building, 52 Zone Ban’ an,Shenzhen,Guangdong518101 CHINA\" d_company=\"us Lee\" d_contact=\"us Lee\" d_tel=\"123123123123\" d_mobile=\"123123123123\" d_address=\"31 Harefoot close\" parcel_quantity=\"1\" j_province=\"guangdong province\" j_city=\"Shenzhen\" d_province=\"\" d_city=\"Northampton\" j_country=\"CN\" j_post_code=\"518100\" d_country=\"RU\" d_post_code=\"XXXX\" cargo_total_weight=\"1.0\" returnsign=\"\" d_email=\"\" operate_flag=\"\" j_county=\"Baoan District\" d_county=\"\" declared_value=\"10.0\" d_deliverycode=\"\"><Cargo name=\"挂钟\" hscode=\"123123123\" ename=\"Wall Clocks\" unit=\"PCE\" count=\"1\" amount=\"10\" weight=\"1.0\"/></Order></Body></Request>";
			java.lang.String _sfexpressService__return = port.sfexpressService(_sfexpressService_arg0);
			logger.debug("sfexpressService.result=" + _sfexpressService__return);

		}

		System.exit(0);
	}

}
