package com.sf.integration.expressservice.service;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import com.xuanfeiyang.erp.App;

/**
 * This class was generated by Apache CXF 3.0.4 2015-03-18T14:39:24.038+08:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "CommonServiceService", wsdlLocation = "http://219.134.187.131:6080/bsp-oisp/ws/expressService?wsdl", targetNamespace = "http://service.expressservice.integration.sf.com/")
public class CommonServiceService extends Service {

	public final static URL WSDL_LOCATION;

	public final static QName SERVICE = new QName("http://service.expressservice.integration.sf.com/",
			"CommonServiceService");
	public final static QName CommonServicePort = new QName("http://service.expressservice.integration.sf.com/",
			"CommonServicePort");
	static {
		URL url = null;
		try {
			url = new URL(App.getConfig("express.sf.russia.url"));
		} catch (MalformedURLException e) {
			java.util.logging.Logger.getLogger(CommonServiceService.class.getName()).log(java.util.logging.Level.INFO,
					"Can not initialize the default wsdl from {0}",
					"http://219.134.187.131:6080/bsp-oisp/ws/expressService?wsdl");
		}
		WSDL_LOCATION = url;
	}

	public CommonServiceService(URL wsdlLocation) {
		super(wsdlLocation, SERVICE);
	}

	public CommonServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public CommonServiceService() {
		super(WSDL_LOCATION, SERVICE);
	}

	// This constructor requires JAX-WS API 2.2. You will need to endorse the
	// 2.2
	// API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS
	// 2.1
	// compliant code instead.
	public CommonServiceService(WebServiceFeature... features) {
		super(WSDL_LOCATION, SERVICE, features);
	}

	// This constructor requires JAX-WS API 2.2. You will need to endorse the
	// 2.2
	// API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS
	// 2.1
	// compliant code instead.
	public CommonServiceService(URL wsdlLocation, WebServiceFeature... features) {
		super(wsdlLocation, SERVICE, features);
	}

	// This constructor requires JAX-WS API 2.2. You will need to endorse the
	// 2.2
	// API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS
	// 2.1
	// compliant code instead.
	public CommonServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	/**
	 *
	 * @return returns IService
	 */
	@WebEndpoint(name = "CommonServicePort")
	public IService getCommonServicePort() {
		return super.getPort(CommonServicePort, IService.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns IService
	 */
	@WebEndpoint(name = "CommonServicePort")
	public IService getCommonServicePort(WebServiceFeature... features) {
		return super.getPort(CommonServicePort, IService.class, features);
	}

}
