package com.ebay.apacshipping.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-04-21T09:24:23.489+08:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://api.apacshipping.ebay.com/", name = "ApacShippingServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ApacShippingServiceSoap {

    /**
     * Get APAC Shipping TrackCode service:<br/>Retrieves the trackcode of a shipping package that includes the item. If the item is not included in any packge, it returns null.
     */
    @WebMethod(operationName = "GetAPACShippingTrackCode", action = "http://api.apacshipping.ebay.com/GetAPACShippingTrackCode")
    @RequestWrapper(localName = "GetAPACShippingTrackCode", targetNamespace = "http://api.apacshipping.ebay.com/", className = "com.ebay.apacshipping.api.GetAPACShippingTrackCode")
    @ResponseWrapper(localName = "GetAPACShippingTrackCodeResponse", targetNamespace = "http://api.apacshipping.ebay.com/", className = "com.ebay.apacshipping.api.GetAPACShippingTrackCodeResponse")
    @WebResult(name = "GetAPACShippingTrackCodeResult", targetNamespace = "http://api.apacshipping.ebay.com/")
    public com.ebay.apacshipping.api.GetAPACShippingTrackCodeResponse2 getAPACShippingTrackCode(
        @WebParam(name = "GetAPACShippingTrackCodeRequest", targetNamespace = "http://api.apacshipping.ebay.com/")
        com.ebay.apacshipping.api.GetAPACShippingTrackCodeRequest getAPACShippingTrackCodeRequest
    );

    /**
     * Recreate APAC shipping package service:<br/>Recreates a already posted shipping package. A shipping package can only be Recreated when its status is In-Transit,Deliver Success or Delivery Fail. For some cases a seller may need to recreate a shipping package. After recreation, the shipping package's status will be reset to New Order.
     */
    @WebMethod(operationName = "RecreateAPACShippingPackage", action = "http://api.apacshipping.ebay.com/RecreateAPACShippingPackage")
    @RequestWrapper(localName = "RecreateAPACShippingPackage", targetNamespace = "http://api.apacshipping.ebay.com/", className = "com.ebay.apacshipping.api.RecreateAPACShippingPackage")
    @ResponseWrapper(localName = "RecreateAPACShippingPackageResponse", targetNamespace = "http://api.apacshipping.ebay.com/", className = "com.ebay.apacshipping.api.RecreateAPACShippingPackageResponse")
    @WebResult(name = "RecreateAPACShippingPackageResult", targetNamespace = "http://api.apacshipping.ebay.com/")
    public com.ebay.apacshipping.api.RecreateAPACShippingPackageResponse2 recreateAPACShippingPackage(
        @WebParam(name = "RecreateAPACShippingPackageRequest", targetNamespace = "http://api.apacshipping.ebay.com/")
        com.ebay.apacshipping.api.RecreateAPACShippingPackageRequest recreateAPACShippingPackageRequest
    );

    /**
     * Get APAC shipping packageStatus service:<br/>Retrieves delivery status of an APAC shipping package.
     */
    @WebMethod(operationName = "GetAPACShippingPackageStatus", action = "http://api.apacshipping.ebay.com/GetAPACShippingPackageStatus")
    @RequestWrapper(localName = "GetAPACShippingPackageStatus", targetNamespace = "http://api.apacshipping.ebay.com/", className = "com.ebay.apacshipping.api.GetAPACShippingPackageStatus")
    @ResponseWrapper(localName = "GetAPACShippingPackageStatusResponse", targetNamespace = "http://api.apacshipping.ebay.com/", className = "com.ebay.apacshipping.api.GetAPACShippingPackageStatusResponse")
    @WebResult(name = "GetAPACShippingPackageStatusResult", targetNamespace = "http://api.apacshipping.ebay.com/")
    public com.ebay.apacshipping.api.GetAPACShippingPackageStatusResponse2 getAPACShippingPackageStatus(
        @WebParam(name = "GetAPACShippingPackageStatusRequest", targetNamespace = "http://api.apacshipping.ebay.com/")
        com.ebay.apacshipping.api.GetAPACShippingPackageStatusRequest getAPACShippingPackageStatusRequest
    );

    /**
     * Get APAC shipping labels service:<br/>Retrieve up to 80 APAC shipping package labels at one time in one PDF.
     */
    @WebMethod(operationName = "GetAPACShippingLabels", action = "http://api.apacshipping.ebay.com/GetAPACShippingLabels")
    @RequestWrapper(localName = "GetAPACShippingLabels", targetNamespace = "http://api.apacshipping.ebay.com/", className = "com.ebay.apacshipping.api.GetAPACShippingLabels")
    @ResponseWrapper(localName = "GetAPACShippingLabelsResponse", targetNamespace = "http://api.apacshipping.ebay.com/", className = "com.ebay.apacshipping.api.GetAPACShippingLabelsResponse")
    @WebResult(name = "GetAPACShippingLabelsResult", targetNamespace = "http://api.apacshipping.ebay.com/")
    public com.ebay.apacshipping.api.GetAPACShippingLabelsResponse2 getAPACShippingLabels(
        @WebParam(name = "GetAPACShippingLabelRequest", targetNamespace = "http://api.apacshipping.ebay.com/")
        com.ebay.apacshipping.api.GetAPACShippingLabelsRequest getAPACShippingLabelRequest
    );

    /**
     * Get APAC shipping package detail service:<br/>Retrieves an APAC shipping package.
     */
    @WebMethod(operationName = "GetAPACShippingPackage", action = "http://api.apacshipping.ebay.com/GetAPACShippingPackage")
    @RequestWrapper(localName = "GetAPACShippingPackage", targetNamespace = "http://api.apacshipping.ebay.com/", className = "com.ebay.apacshipping.api.GetAPACShippingPackage")
    @ResponseWrapper(localName = "GetAPACShippingPackageResponse", targetNamespace = "http://api.apacshipping.ebay.com/", className = "com.ebay.apacshipping.api.GetAPACShippingPackageResponse")
    @WebResult(name = "GetAPACShippingPackageResult", targetNamespace = "http://api.apacshipping.ebay.com/")
    public com.ebay.apacshipping.api.GetAPACShippingPackageResponse2 getAPACShippingPackage(
        @WebParam(name = "GetAPACShippingPackageRequest", targetNamespace = "http://api.apacshipping.ebay.com/")
        com.ebay.apacshipping.api.GetAPACShippingPackageRequest getAPACShippingPackageRequest
    );

    /**
     * Confirm APAC shipping package service:<br/>Confirms a shipping package. The package information will be uploaded to China Post system. Afterward, the package cannot be canceled or revised.
     */
    @WebMethod(operationName = "ConfirmAPACShippingPackage", action = "http://api.apacshipping.ebay.com/ConfirmAPACShippingPackage")
    @RequestWrapper(localName = "ConfirmAPACShippingPackage", targetNamespace = "http://api.apacshipping.ebay.com/", className = "com.ebay.apacshipping.api.ConfirmAPACShippingPackage")
    @ResponseWrapper(localName = "ConfirmAPACShippingPackageResponse", targetNamespace = "http://api.apacshipping.ebay.com/", className = "com.ebay.apacshipping.api.ConfirmAPACShippingPackageResponse")
    @WebResult(name = "ConfirmAPACShippingPackageResult", targetNamespace = "http://api.apacshipping.ebay.com/")
    public com.ebay.apacshipping.api.ConfirmAPACShippingPackageResponse2 confirmAPACShippingPackage(
        @WebParam(name = "ConfirmAPACShippingPackageRequest", targetNamespace = "http://api.apacshipping.ebay.com/")
        com.ebay.apacshipping.api.ConfirmAPACShippingPackageRequest confirmAPACShippingPackageRequest
    );

    /**
     * Get APAC shipping rate service:<br/>Calculates the shipping cost of an APAC shipping package.
     */
    @WebMethod(operationName = "GetAPACShippingRate", action = "http://api.apacshipping.ebay.com/GetAPACShippingRate")
    @RequestWrapper(localName = "GetAPACShippingRate", targetNamespace = "http://api.apacshipping.ebay.com/", className = "com.ebay.apacshipping.api.GetAPACShippingRate")
    @ResponseWrapper(localName = "GetAPACShippingRateResponse", targetNamespace = "http://api.apacshipping.ebay.com/", className = "com.ebay.apacshipping.api.GetAPACShippingRateResponse")
    @WebResult(name = "GetAPACShippingRateResult", targetNamespace = "http://api.apacshipping.ebay.com/")
    public com.ebay.apacshipping.api.GetAPACShippingRateResponse2 getAPACShippingRate(
        @WebParam(name = "GetAPACShippingRateRequest", targetNamespace = "http://api.apacshipping.ebay.com/")
        com.ebay.apacshipping.api.GetAPACShippingRateRequest getAPACShippingRateRequest
    );

    /**
     * Get APAC shipping label service:<br/>Retrieves an APAC shipping package label in PDF format.
     */
    @WebMethod(operationName = "GetAPACShippingLabel", action = "http://api.apacshipping.ebay.com/GetAPACShippingLabel")
    @RequestWrapper(localName = "GetAPACShippingLabel", targetNamespace = "http://api.apacshipping.ebay.com/", className = "com.ebay.apacshipping.api.GetAPACShippingLabel")
    @ResponseWrapper(localName = "GetAPACShippingLabelResponse", targetNamespace = "http://api.apacshipping.ebay.com/", className = "com.ebay.apacshipping.api.GetAPACShippingLabelResponse")
    @WebResult(name = "GetAPACShippingLabelResult", targetNamespace = "http://api.apacshipping.ebay.com/")
    public com.ebay.apacshipping.api.GetAPACShippingLabelResponse2 getAPACShippingLabel(
        @WebParam(name = "GetAPACShippingLabelRequest", targetNamespace = "http://api.apacshipping.ebay.com/")
        com.ebay.apacshipping.api.GetAPACShippingLabelRequest getAPACShippingLabelRequest
    );

    /**
     * Cancel APAC shipping package service:<br/>Cancels an APAC shipping package. A package can only be canceled when its status is New Order. After cancellation, the record will be permanently removed from database.
     */
    @WebMethod(operationName = "CancelAPACShippingPackage", action = "http://api.apacshipping.ebay.com/CancelAPACShippingPackage")
    @RequestWrapper(localName = "CancelAPACShippingPackage", targetNamespace = "http://api.apacshipping.ebay.com/", className = "com.ebay.apacshipping.api.CancelAPACShippingPackage")
    @ResponseWrapper(localName = "CancelAPACShippingPackageResponse", targetNamespace = "http://api.apacshipping.ebay.com/", className = "com.ebay.apacshipping.api.CancelAPACShippingPackageResponse")
    @WebResult(name = "CancelAPACShippingPackageResult", targetNamespace = "http://api.apacshipping.ebay.com/")
    public com.ebay.apacshipping.api.CancelAPACShippingPackageResponse2 cancelAPACShippingPackage(
        @WebParam(name = "CancelAPACShippingPackageRequest", targetNamespace = "http://api.apacshipping.ebay.com/")
        com.ebay.apacshipping.api.CancelAPACShippingPackageRequest cancelAPACShippingPackageRequest
    );

    /**
     * Add APAC shipping package service:<br/>Creates an APAC shipping package and generate a tracking number for the package. 
     */
    @WebMethod(operationName = "AddAPACShippingPackage", action = "http://api.apacshipping.ebay.com/AddAPACShippingPackage")
    @RequestWrapper(localName = "AddAPACShippingPackage", targetNamespace = "http://api.apacshipping.ebay.com/", className = "com.ebay.apacshipping.api.AddAPACShippingPackage")
    @ResponseWrapper(localName = "AddAPACShippingPackageResponse", targetNamespace = "http://api.apacshipping.ebay.com/", className = "com.ebay.apacshipping.api.AddAPACShippingPackageResponse")
    @WebResult(name = "AddAPACShippingPackageResult", targetNamespace = "http://api.apacshipping.ebay.com/")
    public com.ebay.apacshipping.api.AddAPACShippingPackageResponse2 addAPACShippingPackage(
        @WebParam(name = "AddAPACShippingPackageRequest", targetNamespace = "http://api.apacshipping.ebay.com/")
        com.ebay.apacshipping.api.AddAPACShippingPackageRequest addAPACShippingPackageRequest
    );

    /**
     * Verify APAC Shipping User service:<br/>Verify whether user authorization is success or not.
     */
    @WebMethod(operationName = "VerifyAPACShippingUser", action = "http://api.apacshipping.ebay.com/VerifyAPACShippingUser")
    @RequestWrapper(localName = "VerifyAPACShippingUser", targetNamespace = "http://api.apacshipping.ebay.com/", className = "com.ebay.apacshipping.api.VerifyAPACShippingUser")
    @ResponseWrapper(localName = "VerifyAPACShippingUserResponse", targetNamespace = "http://api.apacshipping.ebay.com/", className = "com.ebay.apacshipping.api.VerifyAPACShippingUserResponse")
    @WebResult(name = "VerifyAPACShippingUserResult", targetNamespace = "http://api.apacshipping.ebay.com/")
    public com.ebay.apacshipping.api.VerifyAPACShippingUserResponse2 verifyAPACShippingUser(
        @WebParam(name = "VerifyAPACShippingUserRequest", targetNamespace = "http://api.apacshipping.ebay.com/")
        com.ebay.apacshipping.api.VerifyAPACShippingUserRequest verifyAPACShippingUserRequest
    );
}
